export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const UPDATE_PROJECT_INFO = "UPDATE_PROJECT_INFO";
export const LOADING_PROJECT = "LOADING_PROJECT";
export const ERROR_PROJECT = "ERROR_PROJECT";