export const FETCH_BACKLOG_TASKS_SUCCESS = 'FETCH_BACKLOG_TASKS_SUCCESS';
export const ADD_TASK_BACKLOG_SUCCESS = 'ADD_TASK_BACKLOG_SUCCESS';
export const REMOVE_TASK_BACKLOG_SUCCESS = 'REMOVE_TASK_BACKLOG_SUCCESS';
export const UPDATE_TASKS_BACKLOG_SUCCESS = 'UPDATE_TASKS_BACKLOG_SUCCESS';
export const BACKLOG_PENDING = 'BACKLOG_PENDING';
export const BACKLOG_ERROR = 'BACKLOG_ERROR';