export const FETCH_BOARD_TASKS_SUCCESS = 'FETCH_BOARD_TASKS_SUCCESS';
export const ADD_TASK_BOARD_SUCCESS = 'ADD_TASK_BOARD_SUCCESS';
export const REMOVE_TASK_BOARD_SUCCESS = 'REMOVE_TASK_BOARD_SUCCESS';
export const UPDATE_TASKS_BOARD_SUCCESS = 'UPDATE_TASKS_BOARD_SUCCESS';
export const BOARD_TASK_PENDING = 'BOARD_TASK_PENDING';
export const BOARD_TASK_ERROR = 'BOARD_TASK_ERROR';