import firebase from 'firebase';

export default class Firebase {
    constructor() {
        // Initializes firebase
        firebase.initializeApp({
            apiKey: `${process.env.REACT_APP_FIREBASE_API_KEY}`,
            authDomain: `${process.env.REACT_APP_FIREBASE_AUTH_DOMAIN}`,
            projectId: `${process.env.REACT_APP_PROJECT_ID}`,
        });

        // Initializes and configures firestore
        this._messagesDb = firebase.firestore();

        this._messagesDb.settings({
            timestampsInSnapshots: true
        });
    }

    // Enables the client-side app to add chat messages to the database
    addProject = async (project) => {
        // Receives a message as a parameters and adds two extra fields:
        // author and createdAt, before adding it to the database
        const createdAt = new Date();
        const author = firebase.auth().currentUser.displayName;

        return await this._messagesDb.collection('projects').add({
            ...project,
            author,
            createdAt
        });
    }

    getCurrentUser = () => firebase.auth().currentUser;

    updateProfile = async (profile) => {
        if (!firebase.auth().currentUser) {
            return;
        }

        await firebase.auth().currentUser.updateProfile({
            displayName: profile.name,
            photoURL: profile.picture
        });
    }

    // Ends firebase session
    signOut = async () => await firebase.auth().signOut();

    // Adds a callback to the state listener that will be called whenever the authentication state changes
    setAuthStateListener = (listener) => firebase.auth().onAuthStateChanged(listener);

    // Adds a callback to the messages collection that is called whenever it's changed
    setMessagesListener = (listener) => this._messagesDb.collection('messages').orderBy('createdAt', 'desc').limit(10).onSnapshot(listener);

    // Receives a custom token generated by the server and uses it to authenticate with Firebase
    setToken = async (token) => await firebase.auth().signInWithCustomToken(token);
}